- platform: workday
  country: 'NO'
  name: 'workday_today'

- platform: workday
  country: 'NO'
  days_offset: 1
  name: 'workday_tomorrow'

- platform: workday
  country: 'NO'
  days_offset: -1
  name: 'workday_yesterday'

- platform: rfxtrx
  automatic_add: false
  devices:
    0b110078018fc1a20a000070:
      name: 'Lagringsrom doer'
      device_class: opening
    0b110000019138020a000070:
      name: 'Entre doer'
      device_class: opening
    0b11003e02b71ffe10000060:
      name: 'Loft balkong doer'
      device_class: opening
    0b110009017846d20a010f70:
      name: Stue terasse doer
      device_class: opening
    0b1100000153bdb60a010f70:
      name: 'Loft gang bevegelse'
      device_class: motion
    0b11002b015e19760a010f60:
      name: 'Loft gang bevegelse2'
      device_class: motion

- platform: template
  sensors:
    trapp_motion_via_light:
      friendly_name: 'Trapp motion via light'
      device_class: motion
      value_template: "{{ is_state('light.trapp', 'on') }}"

- platform: 'bayesian'
  prior: 0.75
  name: 'Oystein Home'
  probability_threshold: 0.95
  observations:
    - entity_id: 'device_tracker.oystein_g8441'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.4a4a4a4a4a4a'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
