- platform: sensibo
  api_key: !secret sensibo_key

#- platform: zwave

- platform: generic_thermostat
  name: Alex Termostat
  heater: switch.fwp_soverom_ovn_switch
  target_sensor: sensor.fms_soverom_temperature
  min_temp: 5
  max_temp: 23
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: generic_thermostat
  name: Mats Termostat
  heater: switch.fwp_mats_ovn_switch
  target_sensor: sensor.fms_mats_temperature
  min_temp: 5
  max_temp: 23
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: generic_thermostat
  name: Emma Linn Termostat
  heater: switch.fwp_emmalinn_ovn_switch
  target_sensor: sensor.fms_emma_linn_temperature
  min_temp: 5
  max_temp: 23
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: generic_thermostat
  name: Misha Termostat
  heater: switch.fwp_am_ovn_switch
  target_sensor: sensor.fms_am_temperature
  min_temp: 5
  max_temp: 23
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: generic_thermostat
  name: Entre Termostat
  heater: switch.fwp_entre_ovn_switch
  target_sensor: sensor.fms_entre_temperature
  min_temp: 5
  max_temp: 27
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: generic_thermostat
  name: Kjokken Termostat
  heater: switch.fwp_kjokken_ovn_switch
  target_sensor: sensor.fms_kjokken_temperature
  min_temp: 5
  max_temp: 27
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  min_cycle_duration:
    seconds: 15
  keep_alive:
    minutes: 3
  away_temp: 5
  initial_operation_mode: "auto"

- platform: mill
  username: !secret mill_user_name
  password: !secret mill_user_password
