- platform: moon

- platform: yr
  name: 'Yr'
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

- platform: yr
  name: 'Yr 24h'
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

- platform: time_date
  display_options:
    - time
    - date
    - date_time

- platform: systemmonitor
  resources:
    - type: last_boot
    - type: since_last_boot
    - type: processor_use
    - type: load_15m
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use_percent

- platform: rfxtrx
  automatic_add: false
  devices:
    0a520904b7000106270269:
      name: Kjokkenvindu Inne
      data_type:
        - Humidity
        - Temperature
    08500705b80000ef69:
      name: Kjokkenvindu Ute
      data_type:
        - Temperature
    085007039700002d79:
      name: Kjokken Kjoleskap
      data_type:
        - Temperature
    08500799d70000fb79:
      name: Kjokken Fryseboks
      data_type:
        - Temperature
    0850071af700010079:
      name: Kjokken Vinskap
      data_type:
        - Temperature
    0a52071c3e0e00f5230279:
      name: Loft bad
      data_type:
        - Temperature
        - Humidity
    0a5207c53d0e00ec230269:
      name: Bad nede
      data_type:
        - Temperature
        - Humidity
    0a5207a52b0e00eb200279:
      name: Stue Bokhylle
      data_type:
        - Temperature
        - Humidity
    0a520721330e00b0240279:
      name: Lagringsrom
      data_type:
        - Temperature
        - Humidity
    0a52070b270e00cc3c0179:
      name: Soverom Nede
      data_type:
        - Temperature
        - Humidity


###############################
#                             #
#        Template             #
#                             #
###############################

- platform: template
  sensors:
    ac_stue_temp_setp:
      friendly_name: 'Varmepumpe Stue Temperature Setpoint'
      value_template: '{{ states.climate.stue.attributes.temperature }}'
      unit_of_measurement: 'C'

    ac_stue_temp_act:
      friendly_name: 'Varmepumpe Stue Temperature Actual'
      value_template: '{{ states.climate.stue.attributes.current_temperature }}'
      unit_of_measurement: 'C'

    ac_stue_humidity:
      friendly_name: 'Varmepumpe Stue Humidity Actual'
      value_template: '{{ states.climate.stue.attributes.current_humidity }}'
      unit_of_measurement: '%'

    ac_loftstue_temp_setp:
      friendly_name: 'Varmepumpe Loftstue Temperature Setpoint'
      value_template: '{{ states.climate.loftstue.attributes.temperature }}'
      unit_of_measurement: 'C'

    ac_loftstue_temp_act:
      friendly_name: 'Varmepumpe Loftstue Temperature Actual'
      value_template: '{{ states.climate.loftstue.attributes.current_temperature }}'
      unit_of_measurement: 'C'

    ac_loftstue_humidity:
      friendly_name: 'Varmepumpe Loftstue Humidity Actual'
      value_template: '{{ states.climate.loftstue.attributes.current_humidity }}'
      unit_of_measurement: '%'

    total_power_usage:
      value_template: >
        {{ ((states.sensor.fwp_am_ovn_power.state | float) +
            (states.sensor.fwp_emmalinn_ovn_power.state | float) +
            (states.sensor.fwp_entre_ovn_power.state | float) +
            (states.sensor.fwp_kjokken_ovn_power.state | float) +
            (states.sensor.fwp_varmtvannsbereder_power.state | float) +
            (states.sensor.fwp_mats_ovn_power.state | float) +
            (states.sensor.fwp_soverom_ovn_power.state | float) +
            (states.sensor.fwp_stue_spots_power.state | float) +
            (states.sensor.soverom_nede_dimmer_power.state | float)) | round(1) }}'
      friendly_name: 'Total power usage'
      unit_of_measurement: 'w'

    total_energy_usage:
      value_template: >
        {{ ((states.sensor.fwp_am_ovn_energy.state | float) +
            (states.sensor.fwp_emmalinn_ovn_energy.state | float) +
            (states.sensor.fwp_entre_ovn_energy.state | float) +
            (states.sensor.fwp_kjokken_ovn_energy.state | float) +
            (states.sensor.fwp_varmtvannsbereder_energy.state | float) +
            (states.sensor.fwp_mats_ovn_energy.state | float) +
            (states.sensor.fwp_soverom_ovn_energy.state | float) +
            (states.sensor.fwp_stue_spots_energy.state | float) +
            (states.sensor.soverom_nede_dimmer_energy.state | float)) | round(1) }}
      friendly_name: 'Total energy usage'
      unit_of_measurement: 'kWh'

    electricity_price_sommerstien_10_max_price:
      value_template: '{{ (states.sensor.electricity_price_sommerstien_10.attributes.max_price | float) | round(3) }}'
      friendly_name: 'Electricity max price'
      unit_of_measurement: 'NOK/kWh'

    electricity_price_sommerstien_10_min_price:
      value_template: '{{ (states.sensor.electricity_price_sommerstien_10.attributes.min_price | float) | round(3) }}'
      friendly_name: 'Electricity min price'
      unit_of_measurement: 'NOK/kWh'

    electricity_price_sommerstien_10_estimated_annual_consumption:
      value_template: '{{ (states.sensor.electricity_price_sommerstien_10.attributes.estimated_annual_consumption | float) | round(3) }}'
      friendly_name: 'Electricity estimated annual consumption'
      unit_of_measurement: 'kWh'


    # Inspired by https://github.com/rytilahti/python-mirobo/issues/4
#    vacuum_status:
#      value_template: '{{ states.vacuum.robbie.attributes.status }}'
#      friendly_name: 'Robbie Status'
#      icon_template: mdi:comment

    # device status
    hjemmepc:
      friendly_name: 'HjemmePC'
      value_template: "{{ 'online' if is_state('device_tracker.hjemmepc', 'home') else 'offline' }}"

    nuc4:
      friendly_name: 'NUC'
      value_template: "{{ 'online' if is_state('device_tracker.nuc4', 'home') else 'offline' }}"

    uck:
      friendly_name: 'UniFi Cloudkey'
      value_template: "{{ 'online' if is_state('device_tracker.uck', 'home') else 'offline' }}"

    tv_loftstue:
      friendly_name: 'TV Loftstue'
      value_template: "{{ 'online' if is_state('device_tracker.tv_loftstue', 'home') else 'offline' }}"

    printer:
      friendly_name: 'Printer'
      value_template: "{{ 'online' if is_state('device_tracker.printer', 'home') else 'offline' }}"

    hassio:
      friendly_name: 'Hassio - Home Assistant'
      value_template: "{{ 'online' if is_state('device_tracker.hassio', 'home') else 'offline' }}"

    wiiu:
      friendly_name: 'Wii U'
      value_template: "{{ 'online' if is_state('device_tracker.wiiu', 'home') else 'offline' }}"

    rp2:
      friendly_name: 'RaspBerry Pi2'
      value_template: "{{ 'online' if is_state('device_tracker.rp2', 'home') else 'offline' }}"

    harmony_hub:
      friendly_name: 'Harmony Hub Stue'
      value_template: "{{ 'online' if is_state('device_tracker.harmony_hub', 'home') else 'offline' }}"

    sensibo_loft:
      friendly_name: 'Sensibo Loft'
      value_template: "{{ 'online' if is_state('device_tracker.sensibo_loft', 'home') else 'offline' }}"

    sensibo_stue:
      friendly_name: 'Sensibo Stue'
      value_template: "{{ 'online' if is_state('device_tracker.sensibo_stue', 'home') else 'offline' }}"

    zyxel_switch_loft:
      friendly_name: 'Zyxel Switch Loft'
      value_template: "{{ 'online' if is_state('device_tracker.zyxel_switch_loft', 'home') else 'offline' }}"

    robbie:
      friendly_name: 'Robbie'
      value_template: "{{ 'online' if is_state('device_tracker.robbie', 'home') else 'offline' }}"

    broadlink_mini:
      friendly_name: 'BroadlinkMini'
      value_template: "{{ 'online' if is_state('device_tracker.rmmini03', 'home') else 'offline' }}"

    tradfri:
      friendly_name: 'Tradfri Gateway'
      value_template: "{{ 'online' if is_state('device_tracker.tradfri', 'home') else 'offline' }}"

    chromecast_audio:
      friendly_name: 'Chromecast Audio'
      value_template: "{{ 'online' if is_state('device_tracker.chromecastaudio', 'home') else 'offline' }}"

    chromecast_stue:
      friendly_name: 'Chromecast Stue'
      value_template: "{{ 'online' if is_state('device_tracker.cc_stue', 'home') else 'offline' }}"

    chromecast_loftstue:
      friendly_name: 'Chromecast Loftstue'
      value_template: "{{ 'online' if is_state('device_tracker.cc_loftstue', 'home') else 'offline' }}"

    sb_touch:
      friendly_name: 'Squeezebox Touch Stue'
      value_template: "{{ 'online' if is_state('device_tracker.sb_touch', 'home') else 'offline' }}"

    sb_boom_kjokken:
      friendly_name: 'Squeezebox Boom Kjokken'
      value_template: "{{ 'online' if is_state('device_tracker.sb_boom_kjokken', 'home') else 'offline' }}"

    sb_boom_bad:
      friendly_name: 'Squeezebox Boom Bad'
      value_template: "{{ 'online' if is_state('device_tracker.sb_boom_bad', 'home') else 'offline' }}"

    samsung_bd_stue:
      friendly_name: 'Samsung BD Stue'
      value_template: "{{ 'online' if is_state('device_tracker.samsung_bd_stue', 'home') else 'offline' }}"

    vekt_bad:
      friendly_name: 'Vekt Bad'
      value_template: "{{ 'online' if is_state('device_tracker.vekt_bad', 'home') else 'offline' }}"
