- platform: moon

- platform: yr
  name: 'Yr'
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

- platform: yr
  name: 'Yr 24h'
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

- platform: tibber
  access_token: !secret tibber_token

- platform: time_date
  display_options:
    - time
    - date
    - date_time

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: rfxtrx
  automatic_add: False
  devices:
    0a520904b7000106270269:
      name: Kjokkenvindu Inne
      data_type:
        - Humidity
        - Temperature
    08500705b80000ef69:
      name: Kjokkenvindu Ute
      data_type:
        - Temperature
    085007039700002d79:
      name: Kjokken Kjoleskap
      data_type:
        - Temperature
    08500799d70000fb79:
      name: Kjokken Fryseboks
      data_type:
        - Temperature
    0850071af700010079:
      name: Kjokken Vinskap
      data_type:
        - Temperature
    0a52071c3e0e00f5230279:
      name: Loft bad
      data_type:
        - Temperature
        - Humidity
    0a5207c53d0e00ec230269:
      name: Bad nede
      data_type:
        - Temperature
        - Humidity
    0a5207a52b0e00eb200279:
      name: Stue Bokhylle
      data_type:
        - Temperature
        - Humidity


###############################
#                             #
#        Template             #
#                             #
###############################

- platform: template
  sensors:
    ac_stue_temp_setp:
      friendly_name: 'Varmepumpe Stue Temperature Setpoint'
      value_template: '{{ states.climate.stue.attributes.temperature }}'
      unit_of_measurement: 'C'

    ac_stue_temp_act:
      friendly_name: 'Varmepumpe Stue Temperature Actual'
      value_template: '{{ states.climate.stue.attributes.current_temperature }}'
      unit_of_measurement: 'C'

    ac_stue_humidity:
      friendly_name: 'Varmepumpe Stue Humidity Actual'
      value_template: '{{ states.climate.stue.attributes.current_humidity }}'
      unit_of_measurement: '%'

    ac_loftstue_temp_setp:
      friendly_name: 'Varmepumpe Loftstue Temperature Setpoint'
      value_template: '{{ states.climate.loftstue.attributes.temperature }}'
      unit_of_measurement: 'C'

    ac_loftstue_temp_act:
      friendly_name: 'Varmepumpe Loftstue Temperature Actual'
      value_template: '{{ states.climate.loftstue.attributes.current_temperature }}'
      unit_of_measurement: 'C'

    ac_loftstue_humidity:
      friendly_name: 'Varmepumpe Loftstue Humidity Actual'
      value_template: '{{ states.climate.loftstue.attributes.current_humidity }}'
      unit_of_measurement: '%'

    total_power_usage:
      value_template: '{{ ((states.sensor.fwp_am_ovn_power.state | float) + (states.sensor.fwp_emmalinn_ovn_power.state | float) + (states.sensor.fwp_entre_ovn_power.state | float) + (states.sensor.fwp_kjokken_ovn_power.state | float) + (states.sensor.fwp_varmtvannsbereder_power.state | float) + (states.sensor.fwp_mats_ovn_power.state | float) + (states.sensor.fwp_soverom_ovn_power.state | float) + (states.sensor.fwp_stue_spots_power.state | float)) | round(1) }}'
      friendly_name: 'Total power usage'
      unit_of_measurement: 'w'

    total_energy_usage:
      value_template: '{{ ((states.sensor.fwp_am_ovn_energy.state | float) + (states.sensor.fwp_emmalinn_ovn_energy.state | float) + (states.sensor.fwp_entre_ovn_energy.state | float) + (states.sensor.fwp_kjokken_ovn_energy.state | float) + (states.sensor.fwp_varmtvannsbereder_energy.state | float) + (states.sensor.fwp_mats_ovn_energy.state | float) + (states.sensor.fwp_soverom_ovn_energy.state | float) + (states.sensor.fwp_stue_spots_energy.state | float)) | round(1) }}'
      friendly_name: 'Total energy usage'
      unit_of_measurement: 'kWh'

    # Inspired by https://github.com/rytilahti/python-mirobo/issues/4
    vacuum_status:
      value_template: '{{ states.vacuum.robbie.attributes.status}}'
      friendly_name: 'Status'
      icon_template: mdi:comment

    # device status
    hjemmepc:
      friendly_name: 'HjemmePC'
      value_template: "{{ 'online' if is_state('device_tracker.hjemmepc', 'home') else 'off' }}"

    uck:
      friendly_name: 'UniFi Cloudkey'
      value_template: "{{ 'online' if is_state('device_tracker.uck', 'home') else 'off' }}"

    tv_loftstue:
      friendly_name: 'TV Loftstue'
      value_template: "{{ 'online' if is_state('device_tracker.tv_loftstue', 'home') else 'off' }}"

    printer:
      friendly_name: 'Printer'
      value_template: "{{ 'online' if is_state('device_tracker.printer', 'home') else 'off' }}"

    hassio:
      friendly_name: 'Hassio - Home Assistant'
      value_template: "{{ 'online' if is_state('device_tracker.hassio', 'home') else 'off' }}"

    wiiu:
      friendly_name: 'Wii U'
      value_template: "{{ 'online' if is_state('device_tracker.wiiu', 'home') else 'off' }}"

    rp2:
      friendly_name: 'RaspBerry Pi2'
      value_template: "{{ 'online' if is_state('device_tracker.rp2', 'home') else 'off' }}"

    harmony_hub:
      friendly_name: 'Harmony Hub Stue'
      value_template: "{{ 'online' if is_state('device_tracker.harmony_hub', 'home') else 'off' }}"

    sensibo_loft:
      friendly_name: 'Sensibo Loft'
      value_template: "{{ 'online' if is_state('device_tracker.sensibo_loft', 'home') else 'off' }}"

    sensibo_stue:
      friendly_name: 'Sensibo Stue'
      value_template: "{{ 'online' if is_state('device_tracker.sensibo_stue', 'home') else 'off' }}"

    zyxel_switch_loft:
      friendly_name: 'Zyxel Switch Loft'
      value_template: "{{ 'online' if is_state('device_tracker.zyxel_switch_loft', 'home') else 'off' }}"

    robbie:
      friendly_name: 'Robbie'
      value_template: "{{ 'online' if is_state('device_tracker.robbie', 'home') else 'off' }}"

    broadlink_mini:
      friendly_name: 'BroadlinkMini'
      value_template: "{{ 'online' if is_state('device_tracker.rmmini03', 'home') else 'off' }}"

    tradfri:
      friendly_name: 'Tradfri Gateway'
      value_template: "{{ 'online' if is_state('device_tracker.tradfri', 'home') else 'off' }}"

    chromecast_audio:
      friendly_name: 'Chromecast Audio'
      value_template: "{{ 'online' if is_state('device_tracker.chromecastaudio', 'home') else 'off' }}"

    chromecast_stue:
      friendly_name: 'Chromecast Stue'
      value_template: "{{ 'online' if is_state('device_tracker.cc_stue', 'home') else 'off' }}"

    chromecast_loftstue:
      friendly_name: 'Chromecast Loftstue'
      value_template: "{{ 'online' if is_state('device_tracker.cc_loftstue', 'home') else 'off' }}"

    sb_touch:
      friendly_name: 'Squeezebox Touch Stue'
      value_template: "{{ 'online' if is_state('device_tracker.sb_touch', 'home') else 'off' }}"

    sb_boom_kjokken:
      friendly_name: 'Squeezebox Boom Kjokken'
      value_template: "{{ 'online' if is_state('device_tracker.sb_boom_kjokken', 'home') else 'off' }}"

    sb_boom_bad:
      friendly_name: 'Squeezebox Boom Bad'
      value_template: "{{ 'online' if is_state('device_tracker.sb_boom_bad', 'home') else 'off' }}"

    samsung_bd_stue:
      friendly_name: 'Samsung BD Stue'
      value_template: "{{ 'online' if is_state('device_tracker.samsung_bd_stue', 'home') else 'off' }}"

    vekt_bad:
      friendly_name: 'Vekt Bad'
      value_template: "{{ 'online' if is_state('device_tracker.vekt_bad', 'home') else 'off' }}"



###############################
#                             #
#    Attributes - batteries   #
#                             #
###############################

- platform: attributes
  friendly_name: 'FMS Soverom battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.fms_soverom

- platform: attributes
  friendly_name: 'FMS AM battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.fms_am

- platform: attributes
  friendly_name: 'FMS Emma Linn battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.fms_emma_linn

- platform: attributes
  friendly_name: 'FMS Mats battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.fms_mats

- platform: attributes
  friendly_name: 'Strips soverom battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_soverom

- platform: attributes
  friendly_name: 'Strips kjokken battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_kjokken

- platform: attributes
  friendly_name: 'Strips Mats battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_mats

- platform: attributes
  friendly_name: 'Strips Emma Linn battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_emmalinn

- platform: attributes
  friendly_name: 'Strips Bad Loft battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_bad_loft

- platform: attributes
  friendly_name: 'Strips Trapp battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - zwave.strips_trapp

- platform: attributes
  friendly_name: 'Alex Misha light vegg dimmer battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.am_sov_vegg_rc

- platform: attributes
  friendly_name: 'Alex Misha light tak RC battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.am_sov_tak_rc

- platform: attributes
  friendly_name: 'EmmaLinn light dimmer battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.el_sov_dimmer

- platform: attributes
  friendly_name: 'Mats light dimmer battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.mats_sov_dimmer

- platform: attributes
  friendly_name: 'Gang Loft light RC battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.loft_gang_rc

- platform: attributes
  friendly_name: 'Stue light RC battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.stue_rc

- platform: attributes
  friendly_name: 'Soverom light dimmer battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.soverom_rc

- platform: attributes
  friendly_name: 'Kjøkken light RC battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.kjkken_spis_rc

- platform: attributes
  friendly_name: 'Entre light RC battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.entre_tak_rc

- platform: attributes
  friendly_name: 'Trapp motion battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
    - sensor.trapp_motion_detector
